import { ContactInfoType } from "@/types";

export default function EmailTemplate(info: ContactInfoType) {
  return `<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>New Contact Form Submission</title>
    </head>
    <body style="margin: 0; padding: 20px; font-family: Arial, sans-serif; background-color: #f9f9f9; color: #333333;">

        <div class="container" style="max-width: 550px; margin: 0 auto; background: #ffffff; padding: 30px; border: 1px solid #e0e0e0; border-radius: 6px;">
            
            <h2 style="margin-top: 0; color: #111111; border-bottom: 2px solid #eeeeee; padding-bottom: 10px; font-size: 20px;">
                Nuevo Mensaje
            </h2>
            
            <table class="data-table" role="presentation" style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                <tr>
                    <th style="width: 30%; padding: 10px; text-align: left; vertical-align: top; border-bottom: 1px solid #eeeeee; font-size: 14px; color: #666666; font-weight: bold;">
                        Nombre:
                    </th>
                    <td style="padding: 10px; text-align: left; vertical-align: top; border-bottom: 1px solid #eeeeee; font-size: 14px;">
                        ${info.nombre}
                    </td>
                </tr>
                <tr>
                    <th style="width: 30%; padding: 10px; text-align: left; vertical-align: top; border-bottom: 1px solid #eeeeee; font-size: 14px; color: #666666; font-weight: bold;">
                        Correo:
                    </th>
                    <td style="padding: 10px; text-align: left; vertical-align: top; border-bottom: 1px solid #eeeeee; font-size: 14px;">
                        <a href="mailto:${info.correo}" style="color: #0066cc; text-decoration: none;">${info.correo}</a>
                    </td>
                </tr>
                <tr>
                    <th style="width: 30%; padding: 10px; text-align: left; vertical-align: top; border-bottom: 1px solid #eeeeee; font-size: 14px; color: #666666; font-weight: bold;">
                        Enviado desde:
                    </th>
                    <td style="padding: 10px; text-align: left; vertical-align: top; border-bottom: 1px solid #eeeeee; font-size: 14px;">
                        <a href="${info.pagina}" style="color: #0066cc; text-decoration: none;">${info.pagina}</a>
                    </td>
                </tr>
                <tr>
                    <th style="width: 30%; padding: 10px; text-align: left; vertical-align: top; border-bottom: 1px solid #eeeeee; font-size: 14px; color: #666666; font-weight: bold;">
                        Mensaje:
                    </th>
                    <td style="padding: 10px; text-align: left; vertical-align: top; border-bottom: 1px solid #eeeeee; font-size: 14px;">
                        <div class="message-box" style="background-color: #f5f5f5; padding: 15px; border-left: 3px solid #cccccc; margin-top: 5px; white-space: pre-wrap;">${info.mensaje}</div>
                    </td>
                </tr>
            </table>

            <div class="footer" style="margin-top: 25px; font-size: 11px; color: #999999; text-align: center;">
                This message was generated by your website's contact form.
            </div>
            
        </div>

    </body>
    </html>`;
}
